### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by piotr-szewczuk**
Fix example app to work on macOS Sequoia. 

@daredoes

### CODE REVIEW

**Comment by piotr-szewczuk** [comment]
From what I can see now removing space in "Awesome App" string would also worked :)

**Comment by SKaplanOfficial** [comment]
The current example works fine for me on Sequoia. What issue are you having? Also, manually calling `super.__init__()` is redundant, as is setting `self.menu` since the `@rumps.clicked` decorator adds menu items if they don't exist yet.

**Comment by piotr-szewczuk** [comment]
Hi, 

on my machine running current example doesn't work. Nothing appears on the menu bar. 
My PR is just modified version of example from:  

#https://rumps.readthedocs.io/en/latest/examples.html.

But as I stated in comment problem was not with lack of __init__ but with space in "Awesome App" title.
I can edit PR to just something like:

`
AwesomeStatusBarApp("Awesome_App").run()
` 

but if this example, with space works for you than probably something else is wrong on my site :/

**Comment by SKaplanOfficial** [comment]
Hm, both the example on GitHub and the one on readthedocs work the same for me. Not sure why the one on readthedocs has redundant lines.

Not sure what the issue on your end might be. Do you use a menubar manager like Ice or Bartender?

**Comment by piotr-szewczuk** [comment]
I used Bartender some time ago but not anymore...
Probably it's time for clean system install :/ 

I can close PR if problem is only on my site only.
BTW thx for this lib, it's pretty cool!

Cheers :)

**Pull request closed without merging**
